services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '${PORT_DATABASE_SERVICE}:${PORT_DATABASE_SERVICE}'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  user-service:
    build: ./user-service
    env_file: ./.env
    ports:
      - '${PORT_USER_SERVICE}:${PORT_USER_SERVICE}'
    depends_on:
      - database

  order-service:
    build: ./order-service
    env_file: ./.env
    ports:
      - '${PORT_ORDER_SERVICE}:${PORT_ORDER_SERVICE}'
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start
      "
    depends_on:
      - database

  production-service:
    build: ./production-service
    env_file: ./.env
    ports:
      - '${PORT_PRODUCTION_SERVICE}:${PORT_PRODUCTION_SERVICE}'
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start
      "
    depends_on:
      - order-service

volumes:
  pgdata:
